// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SP19.P2.Web.DatabaseContext;

namespace SP19.P2.Web.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20190206050734_PaymentOptionDb")]
    partial class PaymentOptionDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SP19.P2.Web.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address");

                    b.Property<int?>("PaymentOptionsPaymentOptionID");

                    b.Property<string>("RelatedUsersName");

                    b.HasKey("CustomerId");

                    b.HasIndex("PaymentOptionsPaymentOptionID");

                    b.HasIndex("RelatedUsersName");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("SP19.P2.Web.Models.PaymentOption", b =>
                {
                    b.Property<int>("PaymentOptionID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BillingAddress");

                    b.Property<string>("Nickname");

                    b.Property<string>("TokenizedCardSystem");

                    b.HasKey("PaymentOptionID");

                    b.ToTable("PaymentOptions");
                });

            modelBuilder.Entity("SP19.P2.Web.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("SP19.P2.Web.Models.User", b =>
                {
                    b.Property<string>("Name")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<string>("Phone");

                    b.Property<int>("RoleId");

                    b.HasKey("Name");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SP19.P2.Web.Models.Customer", b =>
                {
                    b.HasOne("SP19.P2.Web.Models.PaymentOption", "PaymentOptions")
                        .WithMany()
                        .HasForeignKey("PaymentOptionsPaymentOptionID");

                    b.HasOne("SP19.P2.Web.Models.User", "RelatedUsers")
                        .WithMany()
                        .HasForeignKey("RelatedUsersName");
                });

            modelBuilder.Entity("SP19.P2.Web.Models.User", b =>
                {
                    b.HasOne("SP19.P2.Web.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
